export const FORGOT_PASSWORD_REQUEST: string = 'FORGOT_PASSWORD_REQUEST';
export const FORGOT_PASSWORD_SUCCESS: string = 'FORGOT_PASSWORD_SUCCESS';
export const FORGOT_PASSWORD_FAILURE: string = 'FORGOT_PASSWORD_FAILURE';