export const RESET_PASSWORD_REQUEST: string = 'RESET_PASSWORD_REQUEST';
export const RESET_PASSWORD_SUCCESS: string = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE: string = 'RESET_PASSWORD_FAILURE';